function phi2_differenziabile = phi_secondo(alpha,q_2,q_2_p,u)
%PHI_SECONDO
%    PHI2_DIFFERENZIABILE = PHI_SECONDO(ALPHA,Q_2,Q_2_P,U)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    18-Apr-2020 15:25:15

t2 = cos(q_2);
t3 = sin(q_2);
t4 = alpha.*2.0;
t5 = q_2.*-2.0;
t6 = q_2.*2.0;
t7 = alpha+q_2;
t8 = q_2_p.^2;
t9 = cos(t7);
t10 = sin(t7);
t11 = t4+t5;
t12 = t4+t6;
t13 = cos(t11);
t14 = cos(t12);
t15 = sin(t11);
t16 = sin(t12);
phi2_differenziabile = ((u.*5.21275e+10-t2.*t3.*3.451932e+8+t3.*t8.*9.17444e+9-t2.*t10.*3.242448e+10-t3.*t9.*3.24246249e+10+t8.*t10.*8.6177183e+11-t9.*t10.*3.04569036e+12+t2.*u.*4.4e+7+t9.*u.*4.133e+9+t13.*u.*5.725e+4-t14.*u.*5.725e+4+t3.*t8.*t13.*1.0076e+4+t2.*t8.*t15.*1.0076e+4-t3.*t8.*t14.*1.0076e+4+t2.*t8.*t16.*1.0076e+4+t8.*t10.*t13.*9.46457e+5+t8.*t9.*t15.*9.46457e+5-t8.*t10.*t14.*9.46457e+5+t8.*t9.*t16.*9.46457e+5).*-2.0e+1)./(t13.*-5.846599e+6+t14.*5.846599e+6+t2.*t9.*2.909632e+10+t2.^2.*1.5488e+8+t9.^2.*1.36653512e+12-5.32346881e+12);
