function phi2_differenziabile = phi_secondo(alpha,q_2,q_2_p,u)
%PHI_SECONDO
%    PHI2_DIFFERENZIABILE = PHI_SECONDO(ALPHA,Q_2,Q_2_P,U)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Apr-2020 20:52:37

t2 = cos(q_2);
t3 = sin(q_2);
t4 = alpha.*2.0;
t5 = q_2.*2.0;
t6 = alpha+q_2;
t7 = q_2_p.^2;
t8 = cos(t6);
t9 = sin(t6);
t10 = t4+t5;
t11 = cos(t10);
t12 = sin(t10);
phi2_differenziabile = ((u.*9.3493504e+14-t2.*t3.*3.88826611712e+11-t3.*t7.*1.11386722304e+13+t2.*t9.*4.565371182592e+13+t3.*t8.*4.5653712089216e+13+t7.*t9.*1.3078367574272e+15-t8.*t9.*5.360387773685568e+15-t2.*u.*1.23904e+11+t8.*u.*1.4548072e+13-t11.*u.*1.3e+6-t2.*t7.*t12.*1.5488e+4+t3.*t7.*t11.*1.5488e+4+t7.*t8.*t12.*1.818509e+6-t7.*t9.*t11.*1.818509e+6).*-5.0e+1)./(t11.*3.2201607e+7-t2.*t8.*1.0241842688e+14+t2.^2.*4.3614208e+11+t8.^2.*6.01268178742e+15-2.31587774835456e+16);
