function phi2_differenziabile = phi_secondo(alpha,q_2,q_2_p,u)
%PHI_SECONDO
%    PHI2_DIFFERENZIABILE = PHI_SECONDO(ALPHA,Q_2,Q_2_P,U)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Apr-2020 17:49:39

t2 = cos(q_2);
t3 = sin(q_2);
t4 = alpha.*2.0;
t5 = q_2.*-2.0;
t6 = q_2.*2.0;
t7 = alpha+q_2;
t8 = q_2_p.^2;
t9 = cos(t7);
t10 = sin(t7);
t11 = t4+t5;
t12 = t4+t6;
t13 = cos(t11);
t14 = cos(t12);
t15 = sin(t11);
t16 = sin(t12);
phi2_differenziabile = ((u.*1.52568e+10-t2.*t3.*1.10461824e+8+t3.*t8.*2.6851968e+9-t2.*t10.*1.00036992e+10-t3.*t9.*1.0003698936e+10+t8.*t10.*2.431781352e+11-t9.*t10.*9.059600088e+11+t2.*u.*1.408e+7+t9.*u.*1.27512e+9+t13.*u.*5.0e+3-t14.*u.*5.0e+3+t3.*t8.*t13.*8.8e+2+t2.*t8.*t15.*8.8e+2-t3.*t8.*t14.*8.8e+2+t2.*t8.*t16.*8.8e+2+t8.*t10.*t13.*7.9695e+4+t8.*t9.*t15.*7.9695e+4-t8.*t10.*t14.*7.9695e+4+t8.*t9.*t16.*7.9695e+4).*-8.264462809904671e-3)./(t13.*-2.11e+2+t14.*2.11e+2+t2.*t9.*3.70944e+6+t2.^2.*2.048e+4+t9.^2.*1.6796808e+8-6.4383696e+8);
