function theta2_differenziabile = theta_secondo(alpha,q_2,q_2_p,u)
%THETA_SECONDO
%    THETA2_DIFFERENZIABILE = THETA_SECONDO(ALPHA,Q_2,Q_2_P,U)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Apr-2020 18:15:35

t2 = cos(q_2);
t3 = sin(q_2);
t4 = alpha.*2.0;
t5 = q_2.*-2.0;
t6 = q_2.*2.0;
t7 = alpha+q_2;
t8 = q_2_p.^2;
t9 = cos(t7);
t10 = sin(t7);
t11 = t4+t5;
t12 = t4+t6;
theta2_differenziabile = ((t3.*-1.456715304e+9-t10.*1.319237832e+11+u.*1.8568e+8+t2.*u.*6.4e+6+t9.*u.*5.796e+8+t8.*sin(t11).*1.1605e+4+t8.*sin(t12).*1.1605e+4+t2.*t3.*t8.*1.1264e+6+t2.*t8.*t10.*1.020096e+8+t3.*t8.*t9.*1.020096e+8+t8.*t9.*t10.*9.2382444e+9).*1.818181818180165e-2)./(cos(t11).*-2.11e+2+cos(t12).*2.11e+2+t2.*t9.*3.70944e+6+t2.^2.*2.048e+4+t9.^2.*1.6796808e+8-6.4383696e+8);
