function theta2 = theta_secondo(C_m,t)
%THETA_SECONDO
%    THETA2 = THETA_SECONDO(C_M,T)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Apr-2020 16:54:58

t2 = theta(t);
t3 = cos(t2);
t4 = sin(t2);
t5 = diff(t2,t);
t6 = t3.^2;
t7 = t4.^2;
t8 = t5.^2;
theta2 = ((C_m.*2.321e+14-t3.*1.991580470001664e+15-t4.*1.507930490001162e+17+C_m.*t3.*6.625e+14-C_m.*t4.*8.75e+12+t6.*t8.*1.27531458804224e+14-t7.*t8.*1.27531458804224e+14+t3.*t4.*t8.*9.654253125009408e+15).*-1.818181818180165e-2)./(t6.*-1.75562499999744e+14-t7.*3.0625e+10+sin(t2.*2.0).*3.796523e+6+t3.*t4.*4.6375e+12+7.47488600000512e+14);
