function theta2_ris = theta_secondo(C_m,alpa,q_2,q_2_p)
%THETA_SECONDO
%    THETA2_RIS = THETA_SECONDO(C_M,Q_2,Q_2_P)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    08-Apr-2020 21:01:44
ris = theta_secondo_sub(C_m,alpa,q_2,q_2_p);
if ris<1000
   theta2_ris = ris;
else
    theta2_ris =1000;
end